services:
  - type: web
    name: svv-webhook-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    # startCommand: python flask_app.py
    startCommand: python main_app.py
    envVars:
      - key: BYBIT_API_KEY
        value: 
      - key: BYBIT_API_SECRET  
        value: 
